version: "3.8"

services:
  judol-api:
    build: .
    ports:
      - "7000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
      - nltk_data:/home/appuser/nltk_data
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Optional: Add a simple web server for serving static files (demo.html, etc.)
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./demo.html:/usr/share/nginx/html/demo.html
      - ./api-tester.html:/usr/share/nginx/html/index.html
      - ./test_page.html:/usr/share/nginx/html/test_page.html
      - ./extension:/usr/share/nginx/html/extension
    depends_on:
      - judol-api
    restart: unless-stopped

volumes:
  nltk_data:
  redis_data:
